=== fbientrigo/dihiggs_boundary/lib/higgstools-v1.2/json/PairProductionLimit.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://gitlab.com/higgsbounds/higgstools/-/raw/develop/json/PairProductionLimit.schema.json",
    "type": "object",
    "title": "Pair Production Limit",
    "description": "A 95% C.L. limit on the rate of a Higgs::predictions::PairProductionProcess that only depends on the masses of the involved BSM particles.\n The examples show: \n\n 1. A LHC search for non-resonant h125 pair production in the `4b` final state.\n 2. A LEP search for `ee -> h1 h2 -> bb tautau`. \n\n The data-grids in the examples are restricted to the first and last mass points for brevity.",
    "examples": [
        {
            "limitClass": "PairProductionLimit",
            "id": 181011854,
            "reference": "1810.11854",
            "source": "Tab. 5",
            "citeKey": "CMS:2018sxu",
            "collider": "LHC13",
            "experiment": "CMS",
            "luminosity": 35.9,
            "process": {
                "firstDecay": [
                    "bb"
                ],
                "secondDecay": [
                    "bb"
                ]
            },
            "analysis": {
                "equalParticleMasses": true,
                "massResolution": {
                    "firstParticle": {
                        "absolute": 40,
                        "relative": 0.0
                    },
                    "secondParticle": {
                        "absolute": 40,
                        "relative": 0.0
                    }
                },
                "grid": {
                    "massFirstParticle": [
                        125.0
                    ]
                },
                "limit": {
                    "observed": [
                        0.847
                    ],
                    "expected": [
                        0.419
                    ]
                }
            }
        },
        {
            "limitClass": "PairProductionLimit",
            "id": 60204220,
            "reference": "hep-ex/0602042",
            "source": "Fig 5c,d",
            "citeKey": "ALEPH:2006tnd",
            "collider": "LEP",
            "experiment": "LEPComb",
            "luminosity": 2.6,
            "process": {
                "firstDecay": [
                    "tautau"
                ],
                "secondDecay": [
                    "bb"
                ]
            },
            "analysis": {
                "massResolution": {
                    "firstParticle": {
                        "absolute": 3,
                        "relative": 0
                    },
                    "secondParticle": {
                        "absolute": 3,
                        "relative": 0
                    }
                },
                "grid": {
                    "massFirstParticle": [
                        10.0,
                        180.0
                    ],
                    "massSecondParticle": [
                        3.0,
                        180.0
                    ]
                },
                "limit": {
                    "observed": [
                        0.00056,
                        0.81033,
                        111.9377,
                        1000000.0
                    ],
                    "expected": [
                        0.0006,
                        0.8400,
                        100.87,
                        1000000.0
                    ]
                }
            }
        }
    ],
    "required": [
        "limitClass",
        "id",
        "reference",
        "source",
        "citeKey",
        "collider",
        "experiment",
        "luminosity",
        "process",
        "analysis"
    ],
    "properties": {
        "limitClass": {
            "const": "PairProductionLimit"
        },
        "id": {
            "$ref": "CommonDefs.schema.json#/id"
        },
        "reference": {
            "$ref": "CommonDefs.schema.json#/reference"
        },
        "source": {
            "$ref": "CommonDefs.schema.json#/source"
        },
        "citeKey": {
            "$ref": "CommonDefs.schema.json#/citeKey"
        },
        "collider": {
            "$ref": "CommonDefs.schema.json#/collider"
        },
        "experiment": {
            "$ref": "CommonDefs.schema.json#/experiment"
        },
        "luminosity": {
            "$ref": "CommonDefs.schema.json#/luminosity"
        },
        "process": {
            "$ref": "PairProductionProcess.schema.json"
        },
        "constraints": {
            "type": "object",
            "description": "Assumptions made on the particles",
            "properties": {
                "firstParticle": {
                    "$ref": "Constraints.schema.json#/constraints"
                },
                "secondParticle": {
                    "$ref": "Constraints.schema.json#/constraints"
                }
            }
        },
        "analysis": {
            "type": "object",
            "description": "The actual data of the limit and properties of the experimental analysis.",
            "required": [
                "grid",
                "limit"
            ],
            "properties": {
                "massResolution": {
                    "type": "object",
                    "description": "Mass resolution(s) for the particles.",
                    "properties": {
                        "firstParticle": {
                            "$ref": "CommonDefs.schema.json#/massResolution"
                        },
                        "secondParticle": {
                            "$ref": "CommonDefs.schema.json#/massResolution"
                        }
                    }
                },
                "acceptances": {
                    "$ref": "Acceptances.schema.json"
                },
                "equalParticleMasses": {
                    "type": "boolean",
                    "description": "Is the limit given on a 1D (instead of 2D) grid where the particle masses are assumed to be equal?",
                    "default": false
                },
                "grid": {
                    "type": "object",
                    "description": "Defines the grid on which the limits are given. For a PairProductionLimit with distinct particle masses this is the 2D regular grid spanned by `massFirstParticle`, and `massSecondParticle`. If `/analysis/equalParticleMasses` is true `massSecondParticle` is not required and the 1D grid `massFirstParticle` is used.",
                    "properties": {
                        "massFirstParticle": {
                            "$ref": "CommonDefs.schema.json#/massGrid"
                        },
                        "massSecondParticle": {
                            "$ref": "CommonDefs.schema.json#/massGrid"
                        }
                    },
                    "required": [
                        "massFirstParticle"
                    ],
                    "additionalProperties": false
                },
                "limit": {
                    "type": "object",
                    "description": "The actual data of the 95% C.L. limit **in `pb`**. The 1D `observed` and `expected` arrays are row-major-order flattened versions of the limits on the regular grid spanned by the masses. \nIf `/analysis/equalParticleMasses` is false, this is `limits[massFirstParticle, massSecondParticle]` defined on the regular grid spanned by `/analysis/grid/massFirstParticle`, and `/analysis/grid/massSecondParticle`; \nif it is true this is `limits[massFirstParticle]` defined on the grid `/analysis/grid/massFirstParticle`.",
                    "properties": {
                        "observed": {
                            "$ref": "CommonDefs.schema.json#/observedLimit"
                        },
                        "expected": {
                            "$ref": "CommonDefs.schema.json#/expectedLimit"
                        }
                    },
                    "required": [
                        "observed",
                        "expected"
                    ],
                    "additionalProperties": false
                }
            },
            "if": {
                "properties": {
                    "equalParticleMasses": {
                        "const": false
                    }
                }
            },
            "then": {
                "properties": {
                    "grid": {
                        "required": [
                            "massSecondParticle"
                        ]
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/doubleCharge/HH/ee/nonres_LHC8_ATLAS_20.json
{
    "limitClass": "PairProductionLimit",
    "id": 14120237,
    "reference": "1412.0237",
    "source": "Fig. 4(a)",
    "citeKey": "ATLAS:2014kca",
    "collider": "LHC8",
    "experiment": "ATLAS",
    "luminosity": 20.3,
    "process": {
        "firstDecay": [
            "eesamesign"
        ],
        "secondDecay": [
            "eesamesign"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "grid": {
            "massFirstParticle": [
                50.1030927835051,
                53.1958762886598,
                56.0824742268041,
                58.9690721649485,
                61.8556701030928,
                65.1546391752577,
                68.0412371134021,
                69.0,
                112.0,
                113.40206185567,
                118.144329896907,
                123.298969072165,
                129.278350515464,
                135.051546391753,
                140.20618556701,
                147.835051546392,
                155.257731958763,
                162.268041237113,
                169.896907216495,
                178.350515463918,
                185.979381443299,
                194.639175257732,
                204.123711340206,
                215.051546391753,
                222.886597938144,
                232.989690721649,
                243.917525773196,
                255.051546391753,
                266.80412371134,
                280.0,
                293.19587628866,
                300.000000000001,
                307.216494845361,
                321.855670103093,
                336.907216494845,
                352.989690721649,
                369.896907216495,
                387.628865979381,
                407.422680412371,
                426.80412371134,
                448.041237113402,
                470.103092783505,
                493.814432989691,
                519.381443298969,
                545.979381443299,
                573.60824742268,
                603.711340206185,
                610.721649484536
            ]
        },
        "limit": {
            "observed": [
                10.9097582227046,
                8.16140079325182,
                11.9022824477871,
                11.1229116445837,
                14.304154254852,
                16.9430501625222,
                11.1229116445837,
                1000000.0,
                1000000.0,
                4.1062499172443,
                3.87467512045613,
                4.33066531720584,
                3.96953372274846,
                3.17761180566086,
                2.96953928880449,
                2.78854817172629,
                3.60348475511829,
                2.61858832289389,
                1.90288159123103,
                1.70252084117965,
                1.60650600385373,
                1.3694766186266,
                1.17308027169156,
                1.05976624867607,
                0.971392974108775,
                1.60650600385373,
                1.22527985738287,
                1.01461790254339,
                1.36286795935578,
                1.68612883828689,
                1.24319087892647,
                0.962040327106479,
                0.737304795871685,
                1.26136372203745,
                0.705894008661876,
                0.576108392224475,
                0.824074330989369,
                0.751710160041978,
                0.562341325190351,
                0.422717687557056,
                0.374566913006292,
                0.422717687557054,
                0.298393883001927,
                0.250703076750966,
                0.199719361093159,
                0.340026374648184,
                0.325540511868505,
                0.295520923520287
            ],
            "expected": [
                11.3402296299968,
                10.0484908257287,
                10.2944948816155,
                11.015819387359,
                13.4323271444295,
                12.1936704589071,
                10.857111194022,
                1000000.0,
                1000000.0,
                5.12960629473252,
                5.10485244371067,
                4.47981937991362,
                3.83736944745241,
                3.76383218896516,
                3.40026374648183,
                2.88458960148464,
                2.44712110276819,
                2.12682174729621,
                2.09617999245313,
                1.98755578879352,
                1.73578446954885,
                1.56811587424569,
                1.56811587424569,
                1.41664327466902,
                1.34974616078987,
                1.40300372319058,
                1.31749173414821,
                1.19022824477872,
                1.21936704589071,
                1.15617935456386,
                1.02944948816155,
                0.93451921456054,
                0.848342898244074,
                0.737304795871683,
                0.804381705940068,
                0.709316946997569,
                0.726682225913272,
                0.63463059962866,
                0.404708995075977,
                0.420677786235032,
                0.461174776770828,
                0.3177611805661,
                0.288458960148466,
                0.234286842373225,
                0.208606449347197,
                0.266974995728804,
                0.28845896014847,
                0.266974995728795
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/singleCharge/HH/taunutaunu/nonres_LEP_LEPComb_3.json
{
    "limitClass": "PairProductionLimit",
    "id": 130160652,
    "reference": "1301.6065",
    "source": "Fig 4(top-left)",
    "citeKey": "ALEPH:2013htx",
    "collider": "LEP",
    "experiment": "LEPComb",
    "luminosity": 2.6,
    "process": {
        "firstDecay": [
            "taunu"
        ],
        "secondDecay": [
            "taunu"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "massResolution": {
            "absolute": 3,
            "relative": 0
        },
        "grid": {
            "massFirstParticle": [
                43.0,
                43.5,
                44.0,
                44.5,
                45.0,
                45.5,
                46.0,
                47.0,
                47.5,
                48.0,
                49.0,
                49.5,
                50.0,
                51.0,
                51.5,
                52.0,
                52.5,
                53.0,
                53.5,
                54.0,
                54.5,
                55.0,
                55.5,
                56.0,
                56.5,
                57.0,
                58.0,
                58.5,
                59.0,
                60.0,
                60.5,
                61.0,
                61.5,
                62.0,
                63.0,
                63.5,
                64.0,
                64.5,
                65.0,
                65.5,
                66.0,
                66.5,
                67.0,
                68.0,
                68.5,
                69.0,
                69.5,
                70.0,
                70.5,
                71.0,
                71.5,
                72.0,
                72.5,
                73.0,
                73.5,
                74.0,
                74.5,
                75.0,
                75.5,
                76.0,
                76.5,
                77.0,
                77.5,
                78.0,
                78.5,
                79.0,
                79.5,
                80.0,
                80.5,
                81.0,
                81.5,
                82.0,
                82.5,
                83.0,
                83.5,
                84.0,
                84.5,
                85.0,
                85.5,
                86.0,
                86.5,
                87.0,
                87.5,
                88.0,
                88.5,
                89.0,
                89.5,
                90.0,
                90.5,
                91.0,
                91.5,
                92.0,
                92.5,
                93.0,
                93.5,
                94.0,
                94.5,
                95.0
            ]
        },
        "limit": {
            "observed": [
                0.12895,
                0.12919,
                0.12945,
                0.12065,
                0.11172,
                0.1124,
                0.1131,
                0.11455,
                0.11476,
                0.11498,
                0.11545,
                0.10209,
                0.0885,
                0.09089,
                0.09213,
                0.0934,
                0.0895,
                0.08554,
                0.0872,
                0.0889,
                0.08981,
                0.09075,
                0.09044,
                0.09012,
                0.09458,
                0.09914,
                0.09423,
                0.09488,
                0.09555,
                0.08753,
                0.09529,
                0.10326,
                0.10117,
                0.09903,
                0.10578,
                0.10415,
                0.10247,
                0.10341,
                0.10437,
                0.11029,
                0.11638,
                0.11423,
                0.11201,
                0.11917,
                0.11814,
                0.11707,
                0.11597,
                0.11484,
                0.11752,
                0.1203,
                0.11853,
                0.11669,
                0.11755,
                0.11844,
                0.12152,
                0.12473,
                0.12808,
                0.13157,
                0.13364,
                0.1358,
                0.13806,
                0.14042,
                0.14118,
                0.14197,
                0.15357,
                0.16575,
                0.16155,
                0.15711,
                0.16737,
                0.17819,
                0.18961,
                0.20168,
                0.21055,
                0.21995,
                0.22991,
                0.24049,
                0.25111,
                0.26243,
                0.2745,
                0.28739,
                0.30705,
                0.32816,
                0.33667,
                0.34577,
                0.35727,
                0.36965,
                0.38303,
                0.39752,
                0.42773,
                0.46085,
                0.48583,
                0.5133,
                0.56159,
                0.6154,
                0.67274,
                0.73722,
                0.83005,
                0.93594
            ],
            "expected": [
                0.12008,
                0.1206,
                0.12114,
                0.11855,
                0.11594,
                0.11647,
                0.11703,
                0.11818,
                0.11805,
                0.11793,
                0.1177,
                0.09831,
                0.07858,
                0.07943,
                0.07988,
                0.08034,
                0.08081,
                0.0813,
                0.0818,
                0.08232,
                0.08316,
                0.08403,
                0.08492,
                0.08583,
                0.08655,
                0.0873,
                0.08885,
                0.08979,
                0.09076,
                0.09278,
                0.09383,
                0.09492,
                0.09604,
                0.09719,
                0.09961,
                0.10087,
                0.10218,
                0.10352,
                0.10491,
                0.10635,
                0.10783,
                0.10936,
                0.11095,
                0.11428,
                0.11604,
                0.11786,
                0.11974,
                0.12169,
                0.12371,
                0.12581,
                0.12799,
                0.13026,
                0.13253,
                0.13489,
                0.13734,
                0.1399,
                0.14256,
                0.14533,
                0.14823,
                0.15125,
                0.1544,
                0.1577,
                0.16115,
                0.16476,
                0.17018,
                0.17588,
                0.18186,
                0.18815,
                0.19477,
                0.20174,
                0.20909,
                0.21686,
                0.22507,
                0.23377,
                0.24298,
                0.25276,
                0.26443,
                0.27686,
                0.29012,
                0.3043,
                0.31947,
                0.33576,
                0.35326,
                0.37212,
                0.39462,
                0.419,
                0.44546,
                0.47427,
                0.50573,
                0.54019,
                0.57806,
                0.61983,
                0.66672,
                0.71887,
                0.77713,
                0.84254,
                0.91638,
                1.00024
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/doubleCharge/HH/emu/nonres_LHC8_ATLAS_20.json
{
    "limitClass": "PairProductionLimit",
    "id": 141202373,
    "reference": "1412.0237",
    "source": "Fig. 10(b)",
    "citeKey": "ATLAS:2014kca",
    "collider": "LHC8",
    "experiment": "ATLAS",
    "luminosity": 20.3,
    "process": {
        "firstDecay": [
            "emusamesign"
        ],
        "secondDecay": [
            "emusamesign"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "grid": {
            "massFirstParticle": [
                50.3952896033889,
                53.4765213836383,
                56.9638569340879,
                60.2432212137499,
                64.5305506573758,
                68.0151720639978,
                72.9237011761588,
                77.4268050540767,
                82.5056466914177,
                87.62791463,
                93.8056452495289,
                99.7340139048996,
                106.267636633818,
                113.218219708248,
                120.795430738868,
                128.786209435213,
                137.170878254535,
                147.61185029122,
                157.843493985204,
                168.698372955593,
                180.784455419765,
                193.282748477748,
                207.819702818215,
                223.178703470458,
                240.385357533319,
                258.610833335455,
                278.481758833055,
                300.399488044621,
                324.980131619013,
                351.001646297866,
                382.129483320315,
                451.997312997611,
                493.370364433181,
                539.872129898924,
                592.730420208837,
                613.223223910929
            ]
        },
        "limit": {
            "observed": [
                8.20174966623336,
                9.58902661840844,
                9.81056166068414,
                6.93454829537257,
                4.99593041065586,
                5.81871479702718,
                6.75112573428946,
                5.05277347964762,
                4.23984274330865,
                4.20743377682988,
                5.90667006090513,
                5.03247644266287,
                2.95098312683432,
                2.36543751287238,
                2.88385048135504,
                2.78637145010002,
                2.19965878266586,
                1.56661107343213,
                1.15030481309596,
                1.56033626627213,
                1.68376204458497,
                1.13683993302193,
                0.812725449999304,
                0.918037315614238,
                0.863572977939438,
                0.824814001098095,
                0.663594795212782,
                0.665990209202847,
                0.974829891668643,
                0.784242437075767,
                0.580132006133916,
                0.501560984840965,
                0.711983891212342,
                0.450404068648858,
                0.313399891900013,
                0.351303807982049
            ],
            "expected": [
                8.48803495199314,
                9.2303516527816,
                9.62533232761308,
                9.69869758464261,
                8.10739070479277,
                8.20037224409618,
                7.36979884808775,
                6.95989293083119,
                6.49800520841981,
                5.75146873557587,
                5.36972468226986,
                4.9,
                3.85354706636362,
                3.19673084063925,
                3.03037169171544,
                2.99568357707949,
                2.47559602581808,
                2.21627330724249,
                1.8881849968571,
                1.76951365353132,
                1.69019317288812,
                1.65808376174432,
                1.44525222810979,
                1.29379905780118,
                1.20320231070894,
                1.0487224661119,
                0.97898716945949,
                0.889806455999314,
                0.799532635335257,
                0.772374324299037,
                0.61897412965341,
                0.558060550338014,
                0.443784703356388,
                0.376519784501143,
                0.334383249452199,
                0.338163383383516
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/doubleCharge/HH/WWWW/nonres_LHC13_ATLAS_36.json
{
    "limitClass": "PairProductionLimit",
    "id": 180801899,
    "reference": "1808.01899",
    "source": "Fig. 5",
    "citeKey": "ATLAS:2018ceg",
    "collider": "LHC13",
    "experiment": "ATLAS",
    "luminosity": 36.1,
    "process": {
        "firstDecay": [
            "WWsamesign"
        ],
        "secondDecay": [
            "WWsamesign"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "grid": {
            "massFirstParticle": [
                200.0,
                300.0,
                400.0,
                500.0,
                600.0,
                700.0
            ]
        },
        "limit": {
            "observed": [
                56.3664122137405,
                52.0610687022901,
                43.6335877862596,
                33.3740458015267,
                26.1374045801527,
                24.0305343511451
            ],
            "expected": [
                37.2213740458015,
                30.1679389312978,
                20.3664122137405,
                18.0763358778626,
                13.9541984732824,
                12.8549618320611
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/doubleCharge/HH/mutau/nonres_LHC8_ATLAS_20.json
{
    "limitClass": "PairProductionLimit",
    "id": 14112921,
    "reference": "1411.2921",
    "source": "Fig. 5(b)",
    "citeKey": "ATLAS:2014vih",
    "collider": "LHC8",
    "experiment": "ATLAS",
    "luminosity": 20.3,
    "process": {
        "firstDecay": [
            "mutausamesign"
        ],
        "secondDecay": [
            "mutausamesign"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "grid": {
            "massFirstParticle": [
                100.0,
                150.0,
                200.0,
                250.0,
                300.0,
                350.0,
                400.0,
                450.0,
                500.0,
                550.0,
                600.0
            ]
        },
        "limit": {
            "observed": [
                24.527606629777,
                9.09118906472884,
                6.01603486985082,
                2.51188643150959,
                1.97948276206971,
                1.35217992132282,
                0.976461607582975,
                0.727895384398318,
                0.77563102502742,
                0.77563102502742,
                0.775631025027418
            ],
            "expected": [
                34.5088935216415,
                13.7382379588326,
                9.23670857187386,
                3.85662042116348,
                2.65544879314094,
                1.55992403007499,
                1.35217992132282,
                1.1814457737999,
                1.1814457737999,
                1.20992547441196,
                1.23909170111345
            ]
        }
    }
}
