=== fbientrigo/dihiggs_boundary/lib/higgstools-v1.2/json/PairProductionLimit.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://gitlab.com/higgsbounds/higgstools/-/raw/develop/json/PairProductionLimit.schema.json",
    "type": "object",
    "title": "Pair Production Limit",
    "description": "A 95% C.L. limit on the rate of a Higgs::predictions::PairProductionProcess that only depends on the masses of the involved BSM particles.\n The examples show: \n\n 1. A LHC search for non-resonant h125 pair production in the `4b` final state.\n 2. A LEP search for `ee -> h1 h2 -> bb tautau`. \n\n The data-grids in the examples are restricted to the first and last mass points for brevity.",
    "examples": [
        {
            "limitClass": "PairProductionLimit",
            "id": 181011854,
            "reference": "1810.11854",
            "source": "Tab. 5",
            "citeKey": "CMS:2018sxu",
            "collider": "LHC13",
            "experiment": "CMS",
            "luminosity": 35.9,
            "process": {
                "firstDecay": [
                    "bb"
                ],
                "secondDecay": [
                    "bb"
                ]
            },
            "analysis": {
                "equalParticleMasses": true,
                "massResolution": {
                    "firstParticle": {
                        "absolute": 40,
                        "relative": 0.0
                    },
                    "secondParticle": {
                        "absolute": 40,
                        "relative": 0.0
                    }
                },
                "grid": {
                    "massFirstParticle": [
                        125.0
                    ]
                },
                "limit": {
                    "observed": [
                        0.847
                    ],
                    "expected": [
                        0.419
                    ]
                }
            }
        },
        {
            "limitClass": "PairProductionLimit",
            "id": 60204220,
            "reference": "hep-ex/0602042",
            "source": "Fig 5c,d",
            "citeKey": "ALEPH:2006tnd",
            "collider": "LEP",
            "experiment": "LEPComb",
            "luminosity": 2.6,
            "process": {
                "firstDecay": [
                    "tautau"
                ],
                "secondDecay": [
                    "bb"
                ]
            },
            "analysis": {
                "massResolution": {
                    "firstParticle": {
                        "absolute": 3,
                        "relative": 0
                    },
                    "secondParticle": {
                        "absolute": 3,
                        "relative": 0
                    }
                },
                "grid": {
                    "massFirstParticle": [
                        10.0,
                        180.0
                    ],
                    "massSecondParticle": [
                        3.0,
                        180.0
                    ]
                },
                "limit": {
                    "observed": [
                        0.00056,
                        0.81033,
                        111.9377,
                        1000000.0
                    ],
                    "expected": [
                        0.0006,
                        0.8400,
                        100.87,
                        1000000.0
                    ]
                }
            }
        }
    ],
    "required": [
        "limitClass",
        "id",
        "reference",
        "source",
        "citeKey",
        "collider",
        "experiment",
        "luminosity",
        "process",
        "analysis"
    ],
    "properties": {
        "limitClass": {
            "const": "PairProductionLimit"
        },
        "id": {
            "$ref": "CommonDefs.schema.json#/id"
        },
        "reference": {
            "$ref": "CommonDefs.schema.json#/reference"
        },
        "source": {
            "$ref": "CommonDefs.schema.json#/source"
        },
        "citeKey": {
            "$ref": "CommonDefs.schema.json#/citeKey"
        },
        "collider": {
            "$ref": "CommonDefs.schema.json#/collider"
        },
        "experiment": {
            "$ref": "CommonDefs.schema.json#/experiment"
        },
        "luminosity": {
            "$ref": "CommonDefs.schema.json#/luminosity"
        },
        "process": {
            "$ref": "PairProductionProcess.schema.json"
        },
        "constraints": {
            "type": "object",
            "description": "Assumptions made on the particles",
            "properties": {
                "firstParticle": {
                    "$ref": "Constraints.schema.json#/constraints"
                },
                "secondParticle": {
                    "$ref": "Constraints.schema.json#/constraints"
                }
            }
        },
        "analysis": {
            "type": "object",
            "description": "The actual data of the limit and properties of the experimental analysis.",
            "required": [
                "grid",
                "limit"
            ],
            "properties": {
                "massResolution": {
                    "type": "object",
                    "description": "Mass resolution(s) for the particles.",
                    "properties": {
                        "firstParticle": {
                            "$ref": "CommonDefs.schema.json#/massResolution"
                        },
                        "secondParticle": {
                            "$ref": "CommonDefs.schema.json#/massResolution"
                        }
                    }
                },
                "acceptances": {
                    "$ref": "Acceptances.schema.json"
                },
                "equalParticleMasses": {
                    "type": "boolean",
                    "description": "Is the limit given on a 1D (instead of 2D) grid where the particle masses are assumed to be equal?",
                    "default": false
                },
                "grid": {
                    "type": "object",
                    "description": "Defines the grid on which the limits are given. For a PairProductionLimit with distinct particle masses this is the 2D regular grid spanned by `massFirstParticle`, and `massSecondParticle`. If `/analysis/equalParticleMasses` is true `massSecondParticle` is not required and the 1D grid `massFirstParticle` is used.",
                    "properties": {
                        "massFirstParticle": {
                            "$ref": "CommonDefs.schema.json#/massGrid"
                        },
                        "massSecondParticle": {
                            "$ref": "CommonDefs.schema.json#/massGrid"
                        }
                    },
                    "required": [
                        "massFirstParticle"
                    ],
                    "additionalProperties": false
                },
                "limit": {
                    "type": "object",
                    "description": "The actual data of the 95% C.L. limit **in `pb`**. The 1D `observed` and `expected` arrays are row-major-order flattened versions of the limits on the regular grid spanned by the masses. \nIf `/analysis/equalParticleMasses` is false, this is `limits[massFirstParticle, massSecondParticle]` defined on the regular grid spanned by `/analysis/grid/massFirstParticle`, and `/analysis/grid/massSecondParticle`; \nif it is true this is `limits[massFirstParticle]` defined on the grid `/analysis/grid/massFirstParticle`.",
                    "properties": {
                        "observed": {
                            "$ref": "CommonDefs.schema.json#/observedLimit"
                        },
                        "expected": {
                            "$ref": "CommonDefs.schema.json#/expectedLimit"
                        }
                    },
                    "required": [
                        "observed",
                        "expected"
                    ],
                    "additionalProperties": false
                }
            },
            "if": {
                "properties": {
                    "equalParticleMasses": {
                        "const": false
                    }
                }
            },
            "then": {
                "properties": {
                    "grid": {
                        "required": [
                            "massSecondParticle"
                        ]
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/singleCharge/HH/cscs/nonres_LEP_LEPComb_3.json
{
    "limitClass": "PairProductionLimit",
    "id": 130160651,
    "reference": "1301.6065",
    "source": "Fig 4(bottom-right)",
    "citeKey": "ALEPH:2013htx",
    "collider": "LEP",
    "experiment": "LEPComb",
    "luminosity": 2.6,
    "process": {
        "firstDecay": [
            "cs"
        ],
        "secondDecay": [
            "cs"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "massResolution": {
            "absolute": 3,
            "relative": 0
        },
        "grid": {
            "massFirstParticle": [
                43.0,
                43.5,
                44.0,
                44.5,
                45.0,
                45.5,
                46.0,
                47.0,
                47.5,
                48.0,
                49.0,
                49.5,
                50.0,
                51.0,
                51.5,
                52.0,
                52.5,
                53.0,
                53.5,
                54.0,
                54.5,
                55.0,
                55.5,
                56.0,
                56.5,
                57.0,
                58.0,
                58.5,
                59.0,
                60.0,
                60.5,
                61.0,
                61.5,
                62.0,
                63.0,
                63.5,
                64.0,
                64.5,
                65.0,
                65.5,
                66.0,
                66.5,
                67.0,
                68.0,
                68.5,
                69.0,
                69.5,
                70.0,
                70.5,
                71.0,
                71.5,
                72.0,
                72.5,
                73.0,
                73.5,
                74.0,
                74.5,
                75.0,
                75.5,
                76.0,
                76.5,
                77.0,
                77.5,
                78.0,
                78.5,
                79.0,
                79.5,
                80.0,
                80.5,
                81.0,
                81.5,
                82.0,
                82.5,
                83.0,
                83.5,
                84.0,
                84.5,
                85.0,
                85.5,
                86.0,
                86.5,
                87.0,
                87.5,
                88.0,
                88.5,
                89.0,
                89.5,
                90.0,
                90.5,
                91.0,
                91.5,
                92.0,
                92.5,
                93.0,
                93.5,
                94.0,
                94.5,
                95.0
            ]
        },
        "limit": {
            "observed": [
                0.20947,
                0.2096,
                0.20352,
                0.17574,
                0.14193,
                0.12072,
                0.09919,
                0.08193,
                0.08114,
                0.08108,
                0.07797,
                0.08243,
                0.08697,
                0.08856,
                0.09331,
                0.09815,
                0.11867,
                0.1396,
                0.16381,
                0.18851,
                0.1788,
                0.16554,
                0.152,
                0.14248,
                0.13276,
                0.12283,
                0.11906,
                0.11712,
                0.11576,
                0.11953,
                0.11578,
                0.11194,
                0.10312,
                0.09408,
                0.08442,
                0.08662,
                0.0962,
                0.11508,
                0.1345,
                0.15178,
                0.16959,
                0.18119,
                0.19316,
                0.21592,
                0.20269,
                0.18902,
                0.1935,
                0.19813,
                0.20743,
                0.21707,
                0.21841,
                0.21981,
                0.21435,
                0.20868,
                0.18408,
                0.16729,
                0.18725,
                0.21877,
                0.21726,
                0.22048,
                0.27122,
                0.32431,
                0.37049,
                0.4189,
                0.45173,
                0.4862,
                0.59896,
                0.71768,
                0.8518,
                0.99334,
                1.11026,
                1.17322,
                1.08348,
                0.88439,
                0.7937,
                0.75338,
                0.78378,
                0.83452,
                0.76641,
                0.69453,
                0.61702,
                0.59251,
                0.6512,
                0.77552,
                0.91034,
                1.11254,
                1.21293,
                1.29884,
                1.50842,
                1.74775,
                1.87456,
                1.94424,
                2.02069,
                2.02591,
                1.81523,
                1.46205,
                1.44761,
                1.59323
            ],
            "expected": [
                0.08324,
                0.08453,
                0.08584,
                0.08717,
                0.08713,
                0.08426,
                0.08135,
                0.08314,
                0.08406,
                0.08501,
                0.08696,
                0.07713,
                0.06714,
                0.07225,
                0.0739,
                0.07559,
                0.07732,
                0.07908,
                0.08068,
                0.08232,
                0.07609,
                0.06974,
                0.0715,
                0.0733,
                0.07514,
                0.07703,
                0.08095,
                0.08299,
                0.08507,
                0.08941,
                0.09208,
                0.09481,
                0.09763,
                0.10052,
                0.10655,
                0.10969,
                0.11293,
                0.11561,
                0.11836,
                0.12121,
                0.12414,
                0.12858,
                0.13315,
                0.14277,
                0.14782,
                0.15305,
                0.15846,
                0.16406,
                0.17134,
                0.17889,
                0.18672,
                0.19484,
                0.20329,
                0.2146,
                0.22636,
                0.23861,
                0.25136,
                0.26466,
                0.29463,
                0.32593,
                0.36109,
                0.39787,
                0.45777,
                0.52056,
                0.58644,
                0.65563,
                0.73594,
                0.82049,
                0.8787,
                0.91142,
                0.91012,
                0.86961,
                0.83327,
                0.79457,
                0.7735,
                0.75093,
                0.74573,
                0.74004,
                0.75146,
                0.76356,
                0.77931,
                0.7961,
                0.82191,
                0.84961,
                0.90175,
                0.95822,
                1.02893,
                1.10598,
                1.19227,
                1.2869,
                1.35894,
                1.43821,
                1.50526,
                1.57934,
                1.6543,
                1.73773,
                1.83109,
                1.93617
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/neutral/HH/gamgambb/nonres_LHC13_ATLAS_308.json
{
    "limitClass": "PairProductionLimit",
    "id": 250703495,
    "reference": "2507.03495",
    "source": "",
    "citeKey": "ATLAS:2025hhd",
    "collider": "LHC13",
    "experiment": "ATLAS",
    "luminosity": 308,
    "process": {
        "firstDecay": [
            "gamgam"
        ],
        "secondDecay": [
            "bb"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "massResolution": {
            "firstParticle": {
                "absolute": 0,
                "relative": 0.015
            },
            "secondParticle": {
                "absolute": 40,
                "relative": 0
            }
        },
        "acceptances": [
            {
            "denominator": [
                [
                    {
                        "effLam": 0
                    },
                    {
                        "constantAcceptance": 8.3926
                    }
                ],
                [
                    {
                        "effLam": 1
                    },
                    {
                        "constantAcceptance": -1.42855
                    }
                ],
                [
                    {
                        "effLam": 2
                    },
                    {
                        "constantAcceptance": 2.68485
                    }                       
                ]
            ],
            "couplingDepAcceptance": [
                [
                    {
                        "effLam": 0
                    },
                    {
                        "constantAcceptance": 8.3926
                    }
                ],
                [
                    {
                        "effLam": 1
                    },
                    {
                        "constantAcceptance": 0.256298
                    }
                ],
                [
                    {
                        "effLam": 2
                    },
                    {
                        "constantAcceptance": 1
                    }                       
                ]
            ]
            }
        ],
        "grid": {
            "massFirstParticle": [
                125.0
            ]
        },
        "limit": {
            "observed": [
                0.00032652880782958976
            ],
            "expected": [
                0.0003179359444656533
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/doubleCharge/HH/mumu/nonres_LHC8_ATLAS_20.json
{
    "limitClass": "PairProductionLimit",
    "id": 141202372,
    "reference": "1412.0237",
    "source": "Fig. 10(c)",
    "citeKey": "ATLAS:2014kca",
    "collider": "LHC8",
    "experiment": "ATLAS",
    "luminosity": 20.3,
    "process": {
        "firstDecay": [
            "mumusamesign"
        ],
        "secondDecay": [
            "mumusamesign"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "grid": {
            "massFirstParticle": [
                49.6907216494845,
                52.9896907216495,
                56.9072164948453,
                60.0,
                64.9484536082474,
                68.6597938144329,
                73.8144329896907,
                78.9690721649484,
                84.9484536082474,
                90.9278350515463,
                97.7319587628866,
                105.979381443299,
                113.814432989691,
                121.855670103093,
                132.164948453608,
                142.886597938144,
                154.020618556701,
                167.01030927835,
                180.824742268041,
                196.907216494845,
                214.845360824742,
                234.639175257732,
                256.907216494845,
                282.886597938144,
                311.958762886598,
                383.917525773196,
                429.072164948454,
                482.886597938144,
                546.391752577319,
                613.19587628866
            ]
        },
        "limit": {
            "observed": [
                1.43805420184307,
                2.76403603285579,
                3.02089902388162,
                2.72102954673638,
                2.17328615138066,
                3.37139243212813,
                4.58931654209824,
                2.04115103665795,
                2.40021262747292,
                2.19612576799276,
                1.63881127933833,
                2.12831704103069,
                1.9070550228713,
                1.59653412799103,
                1.59653412799103,
                1.43055680581135,
                1.65603396365715,
                1.33657455672274,
                0.677444945519431,
                0.931865016329942,
                0.763989519092513,
                0.884405698785044,
                0.917365842146403,
                0.616611117423495,
                0.564181501382351,
                0.663427418885058,
                0.354303717718722,
                0.391298797302338,
                0.280039355352202,
                0.298167867981488
            ],
            "expected": [
                2.48966405503369,
                2.77852205165634,
                2.58244916970259,
                2.54226804939492,
                2.3261024079767,
                2.55559180578661,
                2.51582856745836,
                3.42467805043724,
                1.89711245829871,
                1.647400114911,
                1.54723870586705,
                1.45316707900225,
                1.38638618623085,
                1.30209434198787,
                1.14857381300723,
                1.10730657174038,
                1.01315377955791,
                0.961554474826807,
                0.834987375362759,
                0.830634110356099,
                0.744280537995272,
                0.717539196530025,
                0.663427418885067,
                0.570110628194774,
                0.50027113843267,
                0.418813267670773,
                0.381204286308826,
                0.317469940554654,
                0.244452921910488,
                0.204649277465321
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/doubleCharge/HH/emu/nonres_LHC13_ATLAS_36.json
{
    "limitClass": "PairProductionLimit",
    "id": 1710097483,
    "reference": "1710.09748",
    "source": "Fig. 10(c)",
    "citeKey": "ATLAS:2017xqs",
    "collider": "LHC13",
    "experiment": "ATLAS",
    "luminosity": 36.1,
    "process": {
        "firstDecay": [
            "emusamesign"
        ],
        "secondDecay": [
            "emusamesign"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "grid": {
            "massFirstParticle": [
                250.0,
                300.0,
                350.0,
                400.0,
                450.0,
                500.0,
                550.0,
                600.0,
                650.0,
                700.0,
                750.0,
                800.0,
                850.0,
                900.0,
                950.0,
                1000.0,
                1050.0,
                1100.0,
                1150.0,
                1200.0
            ]
        },
        "limit": {
            "observed": [
                0.272294,
                0.143716,
                0.108805,
                0.105896,
                0.106131,
                0.11102,
                0.123134,
                0.117283,
                0.0944195,
                0.0894191,
                0.0881255,
                0.0896223,
                0.0894858,
                0.0903511,
                0.0927078,
                0.0957511,
                0.0986763,
                0.100678,
                0.101636,
                0.104162
            ],
            "expected": [
                0.206282,
                0.161448,
                0.140529,
                0.136355,
                0.1258,
                0.128059,
                0.124089,
                0.118901,
                0.11023,
                0.105381,
                0.105124,
                0.107248,
                0.10767,
                0.109031,
                0.111663,
                0.114762,
                0.117525,
                0.119147,
                0.119587,
                0.121854
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/doubleCharge/HH/WWWW/nonres_LHC13_ATLAS_139.json
{
    "limitClass": "PairProductionLimit",
    "id": 210111961,
    "reference": "2101.11961",
    "source": "https://www.hepdata.net/record/ins1688938",
    "citeKey": "ATLAS:2021jol",
    "collider": "LHC13",
    "experiment": "ATLAS",
    "luminosity": 139.0,
    "process": {
        "firstDecay": [
            "WWsamesign"
        ],
        "secondDecay": [
            "WWsamesign"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "grid": {
            "massFirstParticle": [
                200.0,
                300.0,
                350.0,
                400.0,
                500.0,
                600.0
            ]
        },
        "limit": {
            "observed": [
                15.025,
                9.6896,
                8.7162,
                7.4858,
                5.5951,
                4.8339
            ],
            "expected": [
                15.111,
                9.4993,
                8.5383,
                6.8682,
                4.8541,
                4.2192
            ]
        }
    }
}
