=== fbientrigo/dihiggs_boundary/lib/higgstools-v1.2/json/PairProductionLimit.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://gitlab.com/higgsbounds/higgstools/-/raw/develop/json/PairProductionLimit.schema.json",
    "type": "object",
    "title": "Pair Production Limit",
    "description": "A 95% C.L. limit on the rate of a Higgs::predictions::PairProductionProcess that only depends on the masses of the involved BSM particles.\n The examples show: \n\n 1. A LHC search for non-resonant h125 pair production in the `4b` final state.\n 2. A LEP search for `ee -> h1 h2 -> bb tautau`. \n\n The data-grids in the examples are restricted to the first and last mass points for brevity.",
    "examples": [
        {
            "limitClass": "PairProductionLimit",
            "id": 181011854,
            "reference": "1810.11854",
            "source": "Tab. 5",
            "citeKey": "CMS:2018sxu",
            "collider": "LHC13",
            "experiment": "CMS",
            "luminosity": 35.9,
            "process": {
                "firstDecay": [
                    "bb"
                ],
                "secondDecay": [
                    "bb"
                ]
            },
            "analysis": {
                "equalParticleMasses": true,
                "massResolution": {
                    "firstParticle": {
                        "absolute": 40,
                        "relative": 0.0
                    },
                    "secondParticle": {
                        "absolute": 40,
                        "relative": 0.0
                    }
                },
                "grid": {
                    "massFirstParticle": [
                        125.0
                    ]
                },
                "limit": {
                    "observed": [
                        0.847
                    ],
                    "expected": [
                        0.419
                    ]
                }
            }
        },
        {
            "limitClass": "PairProductionLimit",
            "id": 60204220,
            "reference": "hep-ex/0602042",
            "source": "Fig 5c,d",
            "citeKey": "ALEPH:2006tnd",
            "collider": "LEP",
            "experiment": "LEPComb",
            "luminosity": 2.6,
            "process": {
                "firstDecay": [
                    "tautau"
                ],
                "secondDecay": [
                    "bb"
                ]
            },
            "analysis": {
                "massResolution": {
                    "firstParticle": {
                        "absolute": 3,
                        "relative": 0
                    },
                    "secondParticle": {
                        "absolute": 3,
                        "relative": 0
                    }
                },
                "grid": {
                    "massFirstParticle": [
                        10.0,
                        180.0
                    ],
                    "massSecondParticle": [
                        3.0,
                        180.0
                    ]
                },
                "limit": {
                    "observed": [
                        0.00056,
                        0.81033,
                        111.9377,
                        1000000.0
                    ],
                    "expected": [
                        0.0006,
                        0.8400,
                        100.87,
                        1000000.0
                    ]
                }
            }
        }
    ],
    "required": [
        "limitClass",
        "id",
        "reference",
        "source",
        "citeKey",
        "collider",
        "experiment",
        "luminosity",
        "process",
        "analysis"
    ],
    "properties": {
        "limitClass": {
            "const": "PairProductionLimit"
        },
        "id": {
            "$ref": "CommonDefs.schema.json#/id"
        },
        "reference": {
            "$ref": "CommonDefs.schema.json#/reference"
        },
        "source": {
            "$ref": "CommonDefs.schema.json#/source"
        },
        "citeKey": {
            "$ref": "CommonDefs.schema.json#/citeKey"
        },
        "collider": {
            "$ref": "CommonDefs.schema.json#/collider"
        },
        "experiment": {
            "$ref": "CommonDefs.schema.json#/experiment"
        },
        "luminosity": {
            "$ref": "CommonDefs.schema.json#/luminosity"
        },
        "process": {
            "$ref": "PairProductionProcess.schema.json"
        },
        "constraints": {
            "type": "object",
            "description": "Assumptions made on the particles",
            "properties": {
                "firstParticle": {
                    "$ref": "Constraints.schema.json#/constraints"
                },
                "secondParticle": {
                    "$ref": "Constraints.schema.json#/constraints"
                }
            }
        },
        "analysis": {
            "type": "object",
            "description": "The actual data of the limit and properties of the experimental analysis.",
            "required": [
                "grid",
                "limit"
            ],
            "properties": {
                "massResolution": {
                    "type": "object",
                    "description": "Mass resolution(s) for the particles.",
                    "properties": {
                        "firstParticle": {
                            "$ref": "CommonDefs.schema.json#/massResolution"
                        },
                        "secondParticle": {
                            "$ref": "CommonDefs.schema.json#/massResolution"
                        }
                    }
                },
                "acceptances": {
                    "$ref": "Acceptances.schema.json"
                },
                "equalParticleMasses": {
                    "type": "boolean",
                    "description": "Is the limit given on a 1D (instead of 2D) grid where the particle masses are assumed to be equal?",
                    "default": false
                },
                "grid": {
                    "type": "object",
                    "description": "Defines the grid on which the limits are given. For a PairProductionLimit with distinct particle masses this is the 2D regular grid spanned by `massFirstParticle`, and `massSecondParticle`. If `/analysis/equalParticleMasses` is true `massSecondParticle` is not required and the 1D grid `massFirstParticle` is used.",
                    "properties": {
                        "massFirstParticle": {
                            "$ref": "CommonDefs.schema.json#/massGrid"
                        },
                        "massSecondParticle": {
                            "$ref": "CommonDefs.schema.json#/massGrid"
                        }
                    },
                    "required": [
                        "massFirstParticle"
                    ],
                    "additionalProperties": false
                },
                "limit": {
                    "type": "object",
                    "description": "The actual data of the 95% C.L. limit **in `pb`**. The 1D `observed` and `expected` arrays are row-major-order flattened versions of the limits on the regular grid spanned by the masses. \nIf `/analysis/equalParticleMasses` is false, this is `limits[massFirstParticle, massSecondParticle]` defined on the regular grid spanned by `/analysis/grid/massFirstParticle`, and `/analysis/grid/massSecondParticle`; \nif it is true this is `limits[massFirstParticle]` defined on the grid `/analysis/grid/massFirstParticle`.",
                    "properties": {
                        "observed": {
                            "$ref": "CommonDefs.schema.json#/observedLimit"
                        },
                        "expected": {
                            "$ref": "CommonDefs.schema.json#/expectedLimit"
                        }
                    },
                    "required": [
                        "observed",
                        "expected"
                    ],
                    "additionalProperties": false
                }
            },
            "if": {
                "properties": {
                    "equalParticleMasses": {
                        "const": false
                    }
                }
            },
            "then": {
                "properties": {
                    "grid": {
                        "required": [
                            "massSecondParticle"
                        ]
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/neutral/HH/gamgamWW/nonres_LHC13_ATLAS_36.json
{
    "limitClass": "PairProductionLimit",
    "id": 1807085671,
    "reference": "1807.08567",
    "source": "Tab. 6",
    "citeKey": "ATLAS:2018hqk",
    "collider": "LHC13",
    "experiment": "ATLAS",
    "luminosity": 36.1,
    "process": {
        "firstDecay": [
            "gamgam"
        ],
        "secondDecay": [
            "WW"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "massResolution": {
            "firstParticle": {
                "absolute": 3.4,
                "relative": 0
            },
            "secondParticle": {
                "absolute": 40,
                "relative": 0
            }
        },
        "grid": {
            "massFirstParticle": [
                125.0
            ]
        },
        "limit": {
            "observed": [
                0.0075
            ],
            "expected": [
                0.0053
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/neutral/HH/bbVV/nonres_LHC13_CMS_36.json
{
    "limitClass": "PairProductionLimit",
    "id": 1708041881,
    "reference": "1708.04188",
    "source": "p. 11",
    "citeKey": "CMS:2017rpp",
    "collider": "LHC13",
    "experiment": "CMS",
    "luminosity": 35.9,
    "process": {
        "firstDecay": [
            "bb"
        ],
        "secondDecay": [
            "WW"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "massResolution": {
            "firstParticle": {
                "absolute": 30,
                "relative": 0.0
            },
            "secondParticle": {
                "absolute": 30,
                "relative": 0.0
            }
        },
        "grid": {
            "massFirstParticle": [
                125.0
            ]
        },
        "limit": {
            "observed": [
                1.52620493879918
            ],
            "expected": [
                1.71698055614908
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/neutral/HH/bbVV/nonres_LHC13_ATLAS_36.json
{
    "limitClass": "PairProductionLimit",
    "id": 1811046711,
    "reference": "1811.04671",
    "source": "Tab. 3",
    "citeKey": "ATLAS:2018fpd",
    "collider": "LHC13",
    "experiment": "ATLAS",
    "luminosity": 36.1,
    "process": {
        "firstDecay": [
            "bb"
        ],
        "secondDecay": [
            "WW"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "massResolution": {
            "firstParticle": {
                "absolute": 30,
                "relative": 0.0
            },
            "secondParticle": {
                "absolute": 30,
                "relative": 0.0
            }
        },
        "grid": {
            "massFirstParticle": [
                125.0
            ]
        },
        "limit": {
            "observed": [
                2.5
            ],
            "expected": [
                2.5
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/doubleCharge/HH/mumu/nonres_LHC13_ATLAS_36.json
{
    "limitClass": "PairProductionLimit",
    "id": 1710097482,
    "reference": "1710.09748",
    "source": "Fig. 10(b)",
    "citeKey": "ATLAS:2017xqs",
    "collider": "LHC13",
    "experiment": "ATLAS",
    "luminosity": 36.1,
    "process": {
        "firstDecay": [
            "mumusamesign"
        ],
        "secondDecay": [
            "mumusamesign"
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "grid": {
            "massFirstParticle": [
                250.0,
                300.0,
                350.0,
                400.0,
                450.0,
                500.0,
                550.0,
                600.0,
                650.0,
                700.0,
                750.0,
                800.0,
                850.0,
                900.0,
                950.0,
                1000.0,
                1050.0,
                1100.0,
                1150.0,
                1200.0
            ]
        },
        "limit": {
            "observed": [
                0.280033,
                0.152404,
                0.116169,
                0.113781,
                0.109267,
                0.112274,
                0.0946878,
                0.0985726,
                0.107352,
                0.114919,
                0.120135,
                0.111594,
                0.110122,
                0.107946,
                0.090376,
                0.08628,
                0.0806032,
                0.0808622,
                0.0797627,
                0.0824655
            ],
            "expected": [
                0.185106,
                0.147185,
                0.129784,
                0.128273,
                0.113743,
                0.118052,
                0.108845,
                0.106415,
                0.100707,
                0.0997365,
                0.0997697,
                0.0949715,
                0.0977738,
                0.100314,
                0.0884002,
                0.0877468,
                0.084837,
                0.0852956,
                0.0849057,
                0.0877341
            ]
        }
    }
}

=== fbientrigo/dihiggs_boundary/dataset/hbdataset-v1.7/neutral/HH/combinations/nonres_LHC13_ATLAS_139.json
{
    "limitClass": "PairProductionLimit",
    "id": 240609971,
    "reference": "2406.09971",
    "source": "Fig. Aux 5a",
    "citeKey": "ATLAS:2024ish",
    "collider": "LHC13",
    "experiment": "ATLAS",
    "luminosity": 139,
    "process": {
        "firstDecay": [
            "bb"
        ],
        "secondDecay": [
            "bb",
            "tautau",
            "gamgam"
        ]
    },
    "constraints": {
        "secondParticle": [
            {
            "topDominatedHgg": true
            },
            {
                "modelLike": "SMHiggsInterp",
                "process": {
                    "channels": [
                        [
                            "none",
                            "bb"
                        ],
                        [
                            "none",
                            "tautau"
                        ],
                        [
                            "none",
                            "WW"
                        ],
                        [
                            "none",
                            "gamgam"

                        ]

                    ]

                }

            }
        ]
    },
    "analysis": {
        "equalParticleMasses": true,
        "massResolution": {
            "firstParticle": {
                "absolute": 10,
                "relative": 0.0
            },
            "secondParticle": {
                "absolute": 10,
                "relative": 0.0
            }
        },
        "acceptances": [
            {
            "denominator": [
                [
                    {
                        "effLam": 0
                    },
                    {
                        "constantAcceptance": 14.503984888441675
                    }
                ],
                [
                    {
                        "effLam": 1
                    },
                    {
                        "constantAcceptance": -11.559060100569445
                    }
                ],
                [
                    {
                        "effLam": 2
                    },
                    {
                        "constantAcceptance": 2.7708928817955654
                    }                       
                ]
            ],
            "couplingDepAcceptance": [
                [
                    {
                        "effLam": 0
                    },
                    {
                        "constantAcceptance": 10.394260781113084
                    }
                ],
                [
                    {
                        "effLam": 1
                    },
                    {
                        "constantAcceptance":-5.678443111445292
                    }
                ],
                [
                    {
                        "effLam": 2
                    },
                    {
                        "constantAcceptance": 1
                    }                       
                ]
            ]
            }
        ],
        "grid": {
            "massFirstParticle": [
                125.0
            ]
        },
        "limit": {
            "observed": [
                0.04
            ],
            "expected": [
                0.032743
            ]
        }
    }
}
